import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import Editor from '../components/Editor';
import Results from '../components/Results';
import structure from '../data/example-blinds';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [tournament, setTournament] = useState(structure);
  const [enrichedTournament, setEnrichedTournament] = useState(null);

  console.log('ttt', tournament);
  return (
    <div className={styles.container}>
      <Head>
        <title>MTT Patience Factor Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl">
          Patience Factor Calculator
        </h1>

        <p className={styles.description}>
          Skill level estimate for MTT poker tournaments.
          Based on Arnold Snyders Patience Factor from his book <a href="https://www.amazon.co.uk/Poker-Tournament-Formula-Arnold-Snyder/dp/1580422039">The Poker Tournament Formula</a>
        </p>

        <Editor tournament={tournament} setTournament={setTournament} enrichedTournament={enrichedTournament} />
        <Results tournament={tournament} setTournament={setTournament} setEnrichedTournament={setEnrichedTournament} />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
